### ISSUE TITLE
https网络协议下，选择keyFile之后，依旧提示未选择任何文件

### ISSUE THREAD

**Issue by okamiv** [workpieces/etcdwp#12]
<img width="305" alt="image" src="https://user-images.githubusercontent.com/21301874/175489280-185e8c86-e2c6-46a5-83e6-2c39a0c3286d.png">

**Comment by zlbfzl2000** [comment]
好的，我查看一下，稍后给你回复

**Comment by Dream403** [comment]
> <img alt="image" width="305" src="https://user-images.githubusercontent.com/21301874/175489280-185e8c86-e2c6-46a5-83e6-2c39a0c3286d.png">

刚刚测试发现了这个问题，稍后修复这个bug

**Comment by Dream403** [comment]
>1、感谢您的使用，欢迎继续提交问题和建议
>2、问题已经修复，由于重构代码导致的不小心造成的bug，给您带来用户体验不够太好，实在抱歉
>3、请升级v1.1.1版本，苹果商店正在走审核流程，可以通过当前去下载dmg包
