### ISSUE TITLE
第二次打开新建的Client数据就没了

### ISSUE THREAD

**Issue by guaidashu** [workpieces/etcdwp#14]
第二次打开新建的Client数据就没了
<img width="616" alt="image" src="https://user-images.githubusercontent.com/17829682/176805750-fff734ed-f368-4cb0-8d5e-2d468292533e.png">

**Comment by Dream403** [comment]
强刷新是否有相应的数据吗？我这边尝试复现一下

**Comment by Dream403** [comment]
你这个版本是多少，更新新的版本查看是否会复现 ，我在新的版本测试无法复现

**Comment by opvexe** [comment]
> 第二次打开新建的Client数据就没了 <img alt="image" width="616" src="https://user-images.githubusercontent.com/17829682/176805750-fff734ed-f368-4cb0-8d5e-2d468292533e.png">

首先，您先告诉我们你目前使用的etcdwp是哪个版本。
其次，您告诉下我们，您的macos系统版本是哪个。
如果断开了client服务，您可以点击右侧开启服务，依然可以重新连接etcd客户端。
数据是保存在etcd服务端，客户端只是方便操作和查看。

**Comment by opvexe** [comment]
> 第二次打开新建的Client数据就没了 <img alt="image" width="616" src="https://user-images.githubusercontent.com/17829682/176805750-fff734ed-f368-4cb0-8d5e-2d468292533e.png">

新的版本已发布，请下载最新版[https://workpieces.github.io/etcdwp/](https://workpieces.github.io/etcdwp/)
