### ISSUE TITLE
打开etcd的用户名密码认证后，客户端就连接不上，但我用etcdctl终端命令操作是没任何问题的 （etcdWp版本是1.1.1，macOs的版本是12.4，etcd的版本是3.4.18）

### ISSUE THREAD

**Issue by skyline-he** [workpieces/etcdwp#15]
这是打开认证的结果：
![image](https://user-images.githubusercontent.com/31242184/177932035-50410af6-8216-4f57-8c5f-8beac0f2da62.png)

<img width="897" alt="image" src="https://user-images.githubusercontent.com/31242184/177932146-275f140e-a841-47cf-9a1f-638e21fb4674.png">

这是关闭认证的结果：
![image](https://user-images.githubusercontent.com/31242184/177932327-bc8da5ed-fca3-4aab-a0f3-3cec076dc106.png)
<img width="868" alt="image" src="https://user-images.githubusercontent.com/31242184/177932418-4cfc944a-4707-4f0a-a93f-76f3a112facc.png">

**Comment by opvexe** [comment]
> 这是打开认证的结果： ![image](https://user-images.githubusercontent.com/31242184/177932035-50410af6-8216-4f57-8c5f-8beac0f2da62.png)
> 
> <img alt="image" width="897" src="https://user-images.githubusercontent.com/31242184/177932146-275f140e-a841-47cf-9a1f-638e21fb4674.png">
> 
> 这是关闭认证的结果： ![image](https://user-images.githubusercontent.com/31242184/177932327-bc8da5ed-fca3-4aab-a0f3-3cec076dc106.png) <img alt="image" width="868" src="https://user-images.githubusercontent.com/31242184/177932418-4cfc944a-4707-4f0a-a93f-76f3a112facc.png">

好的，我们目前已经查看到这个问题。我们这里排查下到底哪里出问题。感谢您的反馈

**Comment by skyline-he** [comment]
有结果了吗，是我操作方式的问题吗？

**Comment by opvexe** [comment]
> 有结果了吗，是我操作方式的问题吗？

已经修复了，最新版本下载使用即可

**Comment by skyline-he** [comment]
好的

**Comment by opvexe** [comment]
> 这是打开认证的结果： ![image](https://user-images.githubusercontent.com/31242184/177932035-50410af6-8216-4f57-8c5f-8beac0f2da62.png)
> 
> <img alt="image" width="897" src="https://user-images.githubusercontent.com/31242184/177932146-275f140e-a841-47cf-9a1f-638e21fb4674.png">
> 
> 这是关闭认证的结果： ![image](https://user-images.githubusercontent.com/31242184/177932327-bc8da5ed-fca3-4aab-a0f3-3cec076dc106.png) <img alt="image" width="868" src="https://user-images.githubusercontent.com/31242184/177932418-4cfc944a-4707-4f0a-a93f-76f3a112facc.png">

请下载最新版,更快更方便。[https://workpieces.github.io/etcdwp/](https://workpieces.github.io/etcdwp/)
