### ISSUE TITLE
链接k8s内部署的etcd3.5故障

### ISSUE THREAD

**Issue by 22826165** [workpieces/etcdwp#20]
etcdWp1.12(26)
创建客户端链接成功,正常获取数据,一段时间后显示400,再也无法链接服务
![image](https://user-images.githubusercontent.com/25676646/179483698-0e1bcdfb-3e64-40c1-9ecc-338335c7e5a5.png)

**Comment by opvexe** [comment]
> etcdWp1.12(26) 创建客户端链接成功,正常获取数据,一段时间后显示400,再也无法链接服务 ![image](https://user-images.githubusercontent.com/25676646/179483698-0e1bcdfb-3e64-40c1-9ecc-338335c7e5a5.png)

看日志输出，似乎是go的context上下文关闭了。这个是我们的疏忽的。我们测试看下能复现这个问题吗

**Comment by chuntaojun** [comment]
> > etcdWp1.12(26) 创建客户端链接成功,正常获取数据,一段时间后显示400,再也无法链接服务 ![image](https://user-images.githubusercontent.com/25676646/179483698-0e1bcdfb-3e64-40c1-9ecc-338335c7e5a5.png)
> 
> 看日志输出，似乎是go的context上下文关闭了。这个是我们的疏忽的。我们测试看下能复现这个问题吗

我这里也发现这个问题了

**Comment by shumintao** [comment]
> > > etcdWp1.12(26) 创建客户端链接成功,正常获取数据,一段时间后显示400,再也无法链接服务 ![image](https://user-images.githubusercontent.com/25676646/179483698-0e1bcdfb-3e64-40c1-9ecc-338335c7e5a5.png)
> > 
> > 
> > 看日志输出，似乎是go的context上下文关闭了。这个是我们的疏忽的。我们测试看下能复现这个问题吗
> 
> 我这里也发现这个问题了

我刚刚测试也发现这个问题了。之前调试都是本地起的etcd,公网上启动etcd，去连接 好像会出现连接成功，超时的问题

**Comment by opvexe** [comment]
> > > etcdWp1.12(26) 创建客户端链接成功,正常获取数据,一段时间后显示400,再也无法链接服务 ![image](https://user-images.githubusercontent.com/25676646/179483698-0e1bcdfb-3e64-40c1-9ecc-338335c7e5a5.png)
> > 
> > 
> > 看日志输出，似乎是go的context上下文关闭了。这个是我们的疏忽的。我们测试看下能复现这个问题吗
> 
> 我这里也发现这个问题了

我刚刚测试也遇到了这个问题，因为之前etcd服务是在本地，连接本地似乎没啥问题。
刚刚我在公网部署了一个etcd服务，连接后发现跟你们一样的问题。
不断的出现上下文超时的问题。
我现在不确认是不是打包的framework有问题。
我可能得花点时间来排查这个问题。

**Comment by opvexe** [comment]
> etcdWp1.12(26) 创建客户端链接成功,正常获取数据,一段时间后显示400,再也无法链接服务 ![image](https://user-images.githubusercontent.com/25676646/179483698-0e1bcdfb-3e64-40c1-9ecc-338335c7e5a5.png)

请下载最新版本 [https://workpieces.github.io/etcdwp/](https://workpieces.github.io/etcdwp/)
