### ISSUE TITLE
bug多如牛毛,希望尽快修复.做得好的话收费也是可以的

### ISSUE THREAD

**Issue by chinaliuhan** [workpieces/etcdwp#22]
bug多如牛毛,希望尽快修复.做得好的话收费也是可以的

1.导出bug,多个配置时,每次导出只会使用第一个配置.
2.连接异常,连点断开后客户端依然显示正常,实际上此时已经断开了.
3.数据显示不可靠,实际上数据已经被删除了,但是还是会显示.或者已经新增的数据不显示.
4.导入bug,多个配置导入时导入到那个配置,完全是随机的.
5.最要命的是,存在多个配置时,你根本不知道当前显示的是哪个配置.你点的配置1,它可能显示的是配置2或者3.

总结:
该版本就完全没有进行测试,自测甚至都咩有.

![image](https://user-images.githubusercontent.com/31755440/199238204-16c4747a-d7b7-4fdb-9b97-89bb397fcce7.png)

**Comment by Dream403** [comment]
感谢支持，非常抱歉给您带来了很不好的用户体验，这个后面版本重构相应功能以及相应样式 ，最近正在构思这方面的问题~~

**Comment by opvexe** [comment]
> bug多如牛毛,希望尽快修复.做得好的话收费也是可以的
> 
> 1.导出bug,多个配置时,每次导出只会使用第一个配置. 2.连接异常,连点断开后客户端依然显示正常,实际上此时已经断开了. 3.数据显示不可靠,实际上数据已经被删除了,但是还是会显示.或者已经新增的数据不显示. 4.导入bug,多个配置导入时导入到那个配置,完全是随机的. 5.最要命的是,存在多个配置时,你根本不知道当前显示的是哪个配置.你点的配置1,它可能显示的是配置2或者3.
> 
> 总结: 该版本就完全没有进行测试,自测甚至都咩有.
> 
> ![image](https://user-images.githubusercontent.com/31755440/199238204-16c4747a-d7b7-4fdb-9b97-89bb397fcce7.png)

其实最近也想把这个做好，但是最近公司项目的事太多。一直没时间修改。之前使用的其他语言打包成xframework，发布后发现有很多没法修复的问题，特别是超时问题。

**Comment by opvexe** [comment]
> bug多如牛毛,希望尽快修复.做得好的话收费也是可以的
> 
> 1.导出bug,多个配置时,每次导出只会使用第一个配置. 2.连接异常,连点断开后客户端依然显示正常,实际上此时已经断开了. 3.数据显示不可靠,实际上数据已经被删除了,但是还是会显示.或者已经新增的数据不显示. 4.导入bug,多个配置导入时导入到那个配置,完全是随机的. 5.最要命的是,存在多个配置时,你根本不知道当前显示的是哪个配置.你点的配置1,它可能显示的是配置2或者3.
> 
> 总结: 该版本就完全没有进行测试,自测甚至都咩有.
> 
> ![image](https://user-images.githubusercontent.com/31755440/199238204-16c4747a-d7b7-4fdb-9b97-89bb397fcce7.png)

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/26895243/222041392-6c22d3c2-5e63-4459-b9da-76ee6dfda040.png">
发版了新的版本，可以去 [https://github.com/workpieces/etcdwp/releases/tag/v2.0.1-beta](https://github.com/workpieces/etcdwp/releases/tag/v2.0.1-beta) 下载新版本。

**Comment by chinaliuhan** [comment]
> > bug多如牛毛,希望尽快修复.做得好的话收费也是可以的
> > 1.导出bug,多个配置时,每次导出只会使用第一个配置. 2.连接异常,连点断开后客户端依然显示正常,实际上此时已经断开了. 3.数据显示不可靠,实际上数据已经被删除了,但是还是会显示.或者已经新增的数据不显示. 4.导入bug,多个配置导入时导入到那个配置,完全是随机的. 5.最要命的是,存在多个配置时,你根本不知道当前显示的是哪个配置.你点的配置1,它可能显示的是配置2或者3.
> > 总结: 该版本就完全没有进行测试,自测甚至都咩有.
> > ![image](https://user-images.githubusercontent.com/31755440/199238204-16c4747a-d7b7-4fdb-9b97-89bb397fcce7.png)
> 
> <img alt="image" width="1102" src="https://user-images.githubusercontent.com/26895243/222041392-6c22d3c2-5e63-4459-b9da-76ee6dfda040.png">
> 
> 发版了新的版本，可以去 [https://github.com/workpieces/etcdwp/releases/tag/v2.0.1-beta](https://github.com/workpieces/etcdwp/releases/tag/v2.0.1-beta) 下载新版本。

![image](https://user-images.githubusercontent.com/31755440/222042507-44b5c8b0-ad37-4ac0-9a80-0c3d14abdbee.png)
用不成

**Comment by opvexe** [comment]
> > > bug多如牛毛,希望尽快修复.做得好的话收费也是可以的
> > > 1.导出bug,多个配置时,每次导出只会使用第一个配置. 2.连接异常,连点断开后客户端依然显示正常,实际上此时已经断开了. 3.数据显示不可靠,实际上数据已经被删除了,但是还是会显示.或者已经新增的数据不显示. 4.导入bug,多个配置导入时导入到那个配置,完全是随机的. 5.最要命的是,存在多个配置时,你根本不知道当前显示的是哪个配置.你点的配置1,它可能显示的是配置2或者3.
> > > 总结: 该版本就完全没有进行测试,自测甚至都咩有.
> > > ![image](https://user-images.githubusercontent.com/31755440/199238204-16c4747a-d7b7-4fdb-9b97-89bb397fcce7.png)
> > 
> > 
> > <img alt="image" width="1102" src="https://user-images.githubusercontent.com/26895243/222041392-6c22d3c2-5e63-4459-b9da-76ee6dfda040.png">
> > 发版了新的版本，可以去 https://github.com/workpieces/etcdwp/releases/tag/v2.0.1-beta 下载新版本。
> 
> ![image](https://user-images.githubusercontent.com/31755440/222042507-44b5c8b0-ad37-4ac0-9a80-0c3d14abdbee.png) 用不成

etcd服务开启了吗 ？

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/26895243/222053299-4acc30db-97b9-4e21-bee2-a39314c54adf.png">
<img width="1051" alt="image" src="https://user-images.githubusercontent.com/26895243/222053324-86b9ba7d-0b1d-469e-a044-f53e3dff81a7.png">
