### ISSUE TITLE
macOS v10 support ？

### ISSUE THREAD

**Issue by PaulXu-cn** [workpieces/etcdwp#23]
能支持下 macOS v10 不？
或者说有什么技术问题支持不了？

**Comment by shumintao** [comment]
> 能支持下 macOS v10 不？
> 或者说有什么技术问题支持不了？

可以支持的，只是flutter 默认是11.0 忘记修改了。

**Comment by opvexe** [comment]
> 能支持下 macOS v10 不？
> 或者说有什么技术问题支持不了？

支持的，文档写错了

**Comment by Dream403** [comment]
最低支持10.14版本

**Comment by PaulXu-cn** [comment]
> > 能支持下 macOS v10 不？
> > 或者说有什么技术问题支持不了？
> 
> 支持的，文档写错了

不仅仅是文档，Apple store 上，也是要求 macOS 11.0 或更高。

我手动下载release里的，试了下 v10.15 可用。

**Comment by opvexe** [comment]
> > > 能支持下 macOS v10 不？
> > > 或者说有什么技术问题支持不了？
> > 
> > 
> > 支持的，文档写错了
> 
> 不仅仅是文档，Apple store 上，也是要求 macOS 11.0 或更高。
> 
> 我手动下载release里的，试了下 v10.15 可用。

感谢您的使用，有什么功能性添加可以随时反馈。目前版本正处于迭代状态
